# Generated by Django 2.0.4 on 2018-08-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='影音檔案欄位',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('影音', models.FileField(blank=True, upload_to='')),
                ('語言', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
