# Generated by Django 2.0.4 on 2018-08-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='影音檔案欄位',
            name='測試',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
